name: Mirror EmeraldChat.com
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Run scraper
        run: yarn mirror

      - name: Beautify JS code
        run: yarn pretty

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
        
